version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  ytl:
    lang: node12
    handler: ./ytl
    image: ytl:latest
#  v60:
#    lang: java11-vert-x
#    handler: ./v60
#    image: v60:latest
